baseURL = "https://cyber-protect.io/"
languageCode = "en-us"
title = "Cyber-Protect.io"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id="G-RHGFS34B8B"

  [params.logo]
    mobile = "images/cp-logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/cp-logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Cyber Protect"

  [params.homepage_meta_tags]
    meta_description = "Cyber-Protect.io mission statement."
    meta_og_title = "Cyber-Protect.io"
    meta_og_type = "website"
    meta_og_url = "https://cyber-protect.io"
    meta_og_image = ""
    meta_og_description = "Cyber-Protect.io mission statement."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "Team"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Partner"
    url = "/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
